CREATE TABLE ALUNOS(ID_ALUNO SERIAL CONSTRAINT PK_ALUNOS PRIMARY KEY, 
                    NOME VARCHAR(70) CONSTRAINT NNNOME NOT NULL, 
                    CPF VARCHAR(14) CONSTRAINT NNCPF NOT NULL,
                    SEXO CHAR CONSTRAINT NNSEXO NOT NULL,
                    DATA_NASCIMENTO DATE CONSTRAINT DATA_NASCIMENTO NOT NULL,
                    EMAIL VARCHAR(100),
                    SERIE VARCHAR (5) CONSTRAINT NNSERIE NOT NULL);
                         
CREATE TABLE PROFESSORES(ID_PROFESSOR SERIAL CONSTRAINT PK_PROFESSORES PRIMARY KEY, 
                         NOME VARCHAR(70) CONSTRAINT NNNOME NOT NULL, 
                         CPF VARCHAR(14) CONSTRAINT NNCPF NOT NULL,
                         SEXO CHAR CONSTRAINT NNSEXO NOT NULL,
                         DATA_NASCIMENTO DATE CONSTRAINT DATA_NASCIMENTO NOT NULL,
                         EMAIL VARCHAR(100),
                         DISCIPLINA VARCHAR(20) CONSTRAINT NNDISCIPLINA NOT NULL);                         
                         
CREATE TABLE ALUNOS_PROFESSOR(ID_ALUNOS_PROFESSOR SERIAL CONSTRAINT PK_ALUNOS_PROFESSOR PRIMARY KEY,
                              ANO INT CONSTRAINT NNANO NOT NULL, 
                              ID_ALUNO INT CONSTRAINT NNID_ALUNO NOT NULL,
                              ID_PROFESSOR INT CONSTRAINT NNID_PROFESSOR NOT NULL,
                              NOTA1 DECIMAL(2,1),
                              NOTA2 DECIMAL(2,1),
                              NOTA3 DECIMAL(2,1),
                              NOTA4 DECIMAL(2,1),
                              CONSTRAINT FK_ALUNOS_PROFESSORES_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
                              CONSTRAINT FK_ALUNOS_PROFESSORES_PROFESSORES FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES(ID_PROFESSOR));                        